import { jsPDF } from "jspdf";
import { EXPORT_DOCUMENT_LABELS, formatCoordinate, formatDate, shortenTx } from "@/lib/complianceUtils";
import type { ExportDocumentType, ProductBatch, SellerAdministrativeProfile, VerificationHistoryEntry } from "@/types/compliance";

const addHeader = (doc: jsPDF, title: string, subtitle: string) => {
  doc.setFillColor(15, 61, 46);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, 14, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(subtitle, 14, 21);
  doc.setTextColor(20, 20, 20);
};

const addFooter = (doc: jsPDF, txHash?: string) => {
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by HerblocX Administrative & Compliance Automation", 14, 287);
  if (txHash) {
    doc.text(`Registry TX: ${shortenTx(txHash)}`, 155, 287);
  }
};

const addSectionTitle = (doc: jsPDF, title: string, y: number) => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 61, 46);
  doc.text(title, 14, y);
  doc.setDrawColor(15, 61, 46);
  doc.line(14, y + 2, 196, y + 2);
  doc.setTextColor(20, 20, 20);
};

const addRows = (doc: jsPDF, rows: Array<[string, string]>, startY: number) => {
  let y = startY;
  doc.setFontSize(9);

  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 16, y);
    doc.setFont("helvetica", "normal");
    const wrapped = doc.splitTextToSize(value || "-", 118);
    doc.text(wrapped, 74, y);
    y += Math.max(7, wrapped.length * 5);
  });

  return y;
};

const getDefaultBatch = (profile: SellerAdministrativeProfile, batch?: ProductBatch) => ({
  batchCode: batch?.batchCode ?? "HBX-DRAFT-BATCH",
  productName: batch?.productName ?? `${profile.simplisiaTypes[0] ?? "Herbal"} Simplisia`,
  quantityKg: batch?.quantityKg ?? 0,
  packaging: batch?.packaging ?? "Packaging details pending",
  exportDestination: batch?.exportDestination ?? profile.destinationMarkets[0] ?? "Destination market pending",
  txHash: batch?.txHash ?? profile.farmerIdentity.txHash,
  harvestDate: batch?.harvestDate ?? new Date().toISOString().split("T")[0],
  processingFacility: batch?.processingFacility ?? "Processing facility pending",
});

export const generateExportDocument = (
  profile: SellerAdministrativeProfile,
  documentType: ExportDocumentType,
  batch?: ProductBatch,
) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const documentTitle = EXPORT_DOCUMENT_LABELS[documentType];
  const displayBatch = getDefaultBatch(profile, batch);
  const issuedDate = formatDate(new Date().toISOString());

  addHeader(doc, documentTitle, `HerblocX export document automation • Issued ${issuedDate}`);

  addSectionTitle(doc, "Exporter / Seller", 40);
  let y = addRows(
    doc,
    [
      ["Legal Name", profile.legalName],
      ["Business Entity", profile.businessEntityName || "Individual Seller"],
      ["NIK / NPWP", `${profile.nik} / ${profile.npwp}`],
      ["NIB / Export License", `${profile.nibNumber} / ${profile.exportLicenseNumber}`],
      ["Registered Address", profile.registeredAddress],
      ["Contact", `${profile.email} • ${profile.phone}`],
    ],
    48,
  );

  addSectionTitle(doc, "Commodity and Batch", y + 4);
  y = addRows(
    doc,
    [
      ["Batch Code", displayBatch.batchCode],
      ["Commodity", displayBatch.productName],
      ["HS Code", profile.hsCode],
      ["Quantity", `${displayBatch.quantityKg.toLocaleString()} kg`],
      ["Packaging", displayBatch.packaging],
      ["Destination Market", displayBatch.exportDestination],
      ["Harvest Date", formatDate(displayBatch.harvestDate)],
      ["Processing Facility", displayBatch.processingFacility],
    ],
    y + 12,
  );

  addSectionTitle(doc, "Farmer Digital Identity", y + 4);
  y = addRows(
    doc,
    [
      ["Farmer ID", profile.farmerIdentity.farmerId],
      ["Public Farmer Name", profile.farmerIdentity.farmerName],
      ["Farm Name", profile.farmerIdentity.farmName],
      ["Farm Location", profile.farmerIdentity.farmLocation],
      ["GPS Coordinate", formatCoordinate(profile.farmerIdentity.coordinates.latitude, profile.farmerIdentity.coordinates.longitude)],
      ["Cultivation Method", profile.farmerIdentity.cultivationMethod],
      ["Land Area", `${profile.farmerIdentity.landAreaHectares} hectares`],
      ["Geo Risk", `${profile.farmerIdentity.protectedZoneStatus} / ${profile.farmerIdentity.deforestationRisk}`],
    ],
    y + 12,
  );

  if (documentType === "buyer_invitation_letter") {
    addSectionTitle(doc, "Invitation Statement", y + 4);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const text = doc.splitTextToSize(
      `We invite qualified international buyers to verify and procure ${displayBatch.productName} from ${profile.businessEntityName || profile.legalName}. This letter confirms that administrative, farmer identity, geotagging, certification, and batch traceability records are maintained in the HerblocX compliance registry.`,
      176,
    );
    doc.text(text, 16, y + 14);
  }

  if (documentType === "bill_of_lading") {
    addSectionTitle(doc, "Transport Particulars", y + 4);
    addRows(
      doc,
      [
        ["Shipper", profile.businessEntityName || profile.legalName],
        ["Consignee", "To order of buyer / issuing bank"],
        ["Port of Loading", "Tanjung Emas Port, Semarang, Indonesia"],
        ["Port of Discharge", displayBatch.exportDestination],
        ["Freight Terms", "Freight prepaid / as per sales contract"],
      ],
      y + 12,
    );
  }

  if (documentType === "commercial_invoice") {
    addSectionTitle(doc, "Invoice Particulars", y + 4);
    addRows(
      doc,
      [
        ["Invoice No.", `INV-${displayBatch.batchCode}`],
        ["Payment Terms", "T/T or LC as agreed"],
        ["Currency", "USD / USDT settlement supported"],
        ["Declared Value", "Auto-populate from confirmed order value"],
      ],
      y + 12,
    );
  }

  if (documentType === "packing_list") {
    addSectionTitle(doc, "Packing Details", y + 4);
    addRows(
      doc,
      [
        ["Gross Weight", `${(displayBatch.quantityKg * 1.04).toFixed(2)} kg`],
        ["Net Weight", `${displayBatch.quantityKg.toFixed(2)} kg`],
        ["Package Count", `${Math.ceil(displayBatch.quantityKg / 25)} bags`],
        ["Marks and Numbers", `${displayBatch.batchCode} / HerblocX traceability QR attached`],
      ],
      y + 12,
    );
  }

  if (documentType === "certificate_of_origin") {
    addSectionTitle(doc, "Origin Declaration", y + 4);
    addRows(
      doc,
      [
        ["Country of Origin", "Indonesia"],
        ["Producing Farm", profile.farmerIdentity.farmName],
        ["Administrative Authority", "Template for chamber / issuing authority completion"],
        ["Traceability Reference", displayBatch.batchCode],
      ],
      y + 12,
    );
  }

  if (documentType === "phytosanitary_certificate") {
    addSectionTitle(doc, "Phytosanitary Template Fields", y + 4);
    addRows(
      doc,
      [
        ["Botanical / Product Description", displayBatch.productName],
        ["Treatment Declaration", "To be completed by authorized plant quarantine officer"],
        ["Inspection Reference", "Quality and microbiology test records attached in HerblocX registry"],
        ["Issuing Authority", "Template for national plant protection organization completion"],
      ],
      y + 12,
    );
  }

  addFooter(doc, displayBatch.txHash);
  doc.save(`${documentTitle.replaceAll(" ", "-").toLowerCase()}-${displayBatch.batchCode}.pdf`);
};

export const generateAllExportDocuments = (profile: SellerAdministrativeProfile, batch?: ProductBatch) => {
  (Object.keys(EXPORT_DOCUMENT_LABELS) as ExportDocumentType[]).forEach((documentType) => {
    generateExportDocument(profile, documentType, batch);
  });
};

export const generateComplianceReport = (
  profile: SellerAdministrativeProfile,
  batch: ProductBatch,
  verification?: VerificationHistoryEntry,
) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  addHeader(doc, "HerblocX Compliance Verification Report", `${batch.batchCode} • ${batch.productName}`);

  addSectionTitle(doc, "Traceability Summary", 40);
  let y = addRows(
    doc,
    [
      ["Batch Code", batch.batchCode],
      ["Product", batch.productName],
      ["Farmer ID", profile.farmerIdentity.farmerId],
      ["Farm Coordinate", formatCoordinate(profile.farmerIdentity.coordinates.latitude, profile.farmerIdentity.coordinates.longitude)],
      ["Harvest Date", formatDate(batch.harvestDate)],
      ["Processing Facility", batch.processingFacility],
      ["Registry TX", batch.txHash],
    ],
    48,
  );

  addSectionTitle(doc, "EUDR Section", y + 4);
  y = addRows(
    doc,
    [
      ["Cut-off Date", batch.eudr.deforestationCutoff],
      ["Risk Level", batch.eudr.riskLevel],
      ["Land Use Evidence", batch.eudr.landUseChangeData],
      ["Polygon TX", batch.eudr.polygonTxHash],
    ],
    y + 12,
  );

  addSectionTitle(doc, "FDA Traceability Section", y + 4);
  y = addRows(
    doc,
    [["Lot Code", batch.fda.traceabilityLotCode], ...batch.fda.criticalTrackingEvents.map((event) => [event.label, `${event.value} • ${shortenTx(event.txHash)}`] as [string, string])],
    y + 12,
  );

  addSectionTitle(doc, "JAS Certification Section", y + 4);
  addRows(
    doc,
    [
      ["Certificate No.", batch.jas.certificateNumber],
      ["Certifying Body", batch.jas.certifyingBody],
      ["Validity", batch.jas.validityPeriod],
      ["Verification", verification?.complianceSummary ?? "Generated from live batch compliance data."],
    ],
    y + 12,
  );

  addFooter(doc, verification?.reportTxHash ?? batch.txHash);
  doc.save(`herblocx-compliance-report-${batch.batchCode}.pdf`);
};
