// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nunkvjgxmzzmwapxaxhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51bmt2amd4bXp6bXdhcHhheGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMzY1ODQsImV4cCI6MjA5MTkxMjU4NH0.KfBZWkilDA6D_MP_Z_49xQ9SmJr7kgGj6OFgq6xZ1B4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});